# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Terra-Store
email: jamie@jduncombe.com
description: > # this means to ignore newlines until "baseurl:"
Terra-Store is an Open Source implementation of the Terraform Registry API with a searchable UI.

Currently the system is under development, check back soon for more details
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://terra-store.github.io/" # the base hostname & protocol for your site
github_username:  terra-store

# Build settings
markdown: kramdown

theme: jekyll-theme-cayman
